services:
  - name: fin-plate-checker
    type: web
    env: python
    plan: free
    repo: https://github.com/Boeng83/pdf-combiner-app
    branch: main
    buildCommand: bash -lc "cd fin_plate_checker && pip install -r requirements.txt"
    startCommand: bash -lc "cd fin_plate_checker && gunicorn backend:app"
    autoDeploy: true
    region: oregon
